name: Commit Checks
on: [push, pull_request]

jobs:
  Check_User:
    runs-on: ubuntu-20.04
    steps:
      - name: Clone OpenVINO
        uses: actions/checkout@v2

      - name: Check email
        uses: higebu/actions-email-domain@v1
        with:
          domains: 'intel.com'

      - name: Get login
        env:
          GITHUB_EMAIL: ${{ github.event.head_commit.author.email }}
        run: echo "$GITHUB_EMAIL"

      - name: Get user info
        run: |
          curl --request POST \
          --url ${{ github.sender.url }}
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --fail

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJSON(job) }}
        run: echo "$JOB_CONTEXT"

      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJSON(steps) }}
        run: echo "$STEPS_CONTEXT"

      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJSON(runner) }}
        run: echo "$RUNNER_CONTEXT"

      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJSON(strategy) }}
        run: echo "$STRATEGY_CONTEXT"

      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJSON(matrix) }}
        run: echo "$MATRIX_CONTEXT"

