name: Commit Checks
on: [push, pull_request]

jobs:
  Check_User:
    runs-on: ubuntu-20.04
    steps:
      - name: Clone OpenVINO
        uses: actions/checkout@v2

      - name: Get email
        env:
          GITHUB_EMAIL: ${{ github.event.head_commit.author.email }}
        run: echo "$GITHUB_EMAIL"

      - name: Get user info
        id: user_info
        run: |
          #curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" ${{ github.event.sender.url }}
          #curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" ${{ github.event.sender.organizations_url }}
          content=`curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" ${{ github.event.sender.url }}`
          echo "::set-output name=user_info_json::$content"

      - name: Out email 2
        run: |
          echo ${{ steps.user_info.outputs.user_info_json }}
          echo "${{ toJSON(steps.user_info.outputs.user_info_json).email }}"

      - name: Out email 2
        if: ${{ github.event.head_commit.author.email != toJSON(steps.user_info.outputs.user_info_json).email }}
        run: |
          echo "Commit email ${{ github.event.head_commit.author.email }} is different from GitHub account $ {{ toJSON(steps.user_info.outputs.user_info_json).email }}"

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Check email
        uses: higebu/actions-email-domain@v1
        with:
          domains: 'Qintel.com'

