name: Commit Checks
on: [push, pull_request]

jobs:
  Check_User:
    runs-on: ubuntu-20.04
    steps:
      - name: Clone OpenVINO
        uses: actions/checkout@v2

      - name: Check email
        uses: higebu/actions-email-domain@v1
        with:
          domains: 'intel.com'

      - name: Get email
        env:
          GITHUB_EMAIL: ${{ github.event.head_commit.author.email }}
        run: echo "$GITHUB_EMAIL"

      - name: Get user info
        run: |
          curl --request POST \
          --url ${{ github.event.sender.url }} \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{}' \
          --fail

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"

